/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\room\room.glb --typescript --output src/components/Room/Room.tsx 
*/

import * as THREE from "three";
import { useContext, useEffect, useRef, type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three/examples/jsm/loaders/GLTFLoader.js";
import SceneContext from "../../contexts/SceneContext/SceneContext";

type GLTFResult = GLTF & {
    nodes: {
        ["Blank_Picture_Frame|Node007|Dupli|_1"]: THREE.Mesh;
        ["Blank_Picture_Frame|Node007|Dupli|_2"]: THREE.Mesh;
        ["Blank_Picture_Frame|Node007|Dupli|_3"]: THREE.Mesh;
        ["Blank_Picture_Frame|Node007|Dupli|_4"]: THREE.Mesh;
        ["Cup001|Cup|Dupli|"]: THREE.Mesh;
        ["Keyboard001|group311988427|Dupli|1_1"]: THREE.Mesh;
        ["Keyboard001|group311988427|Dupli|1_2"]: THREE.Mesh;
        ["Keyboard001|group311988427|Dupli|1_3"]: THREE.Mesh;
        ["Keyboard001|group311988427|Dupli|1_4"]: THREE.Mesh;
        ["Monitor001|iMac|Dupli|"]: THREE.Mesh;
        Cabinet_Bed_Drawer_Tabl_1: THREE.Mesh;
        Cabinet_Bed_Drawer_Tabl_2: THREE.Mesh;
        Cabinet_Bed_Drawer_Tabl_3: THREE.Mesh;
        Chair003_1: THREE.Mesh;
        Chair003_2: THREE.Mesh;
        Chair003_3: THREE.Mesh;
        Chair003_4: THREE.Mesh;
        ["Houseplant-bfLOqIV5uP_1"]: THREE.Mesh;
        ["Houseplant-bfLOqIV5uP_2"]: THREE.Mesh;
        ["Houseplant-bfLOqIV5uP_3"]: THREE.Mesh;
        Light_Desk001_1: THREE.Mesh;
        Light_Desk001_2: THREE.Mesh;
        Light_Desk001_3: THREE.Mesh;
        Mouse: THREE.Mesh;
        Mousepad: THREE.Mesh;
        Node003_1: THREE.Mesh;
        Node003_2: THREE.Mesh;
        Paper_1: THREE.Mesh;
        Paper_2: THREE.Mesh;
        Phone_1: THREE.Mesh;
        Phone_2: THREE.Mesh;
        Phone_3: THREE.Mesh;
        Plane: THREE.Mesh;
        Plane_1: THREE.Mesh;
        Houseplant_mesh: THREE.Mesh;
    };
    materials: {
        ["mat21.009"]: THREE.MeshStandardMaterial;
        ["mat22.006"]: THREE.MeshStandardMaterial;
        ["mat15.007"]: THREE.MeshStandardMaterial;
        ["mat24.003"]: THREE.MeshStandardMaterial;
        ["Mat.006"]: THREE.MeshStandardMaterial;
        ["mat22.011"]: THREE.MeshStandardMaterial;
        ["mat21.013"]: THREE.MeshStandardMaterial;
        ["mat16.006"]: THREE.MeshStandardMaterial;
        ["mat9.002"]: THREE.MeshStandardMaterial;
        ["Mat.008"]: THREE.MeshStandardMaterial;
        wood: THREE.MeshStandardMaterial;
        _defaultMat: THREE.MeshStandardMaterial;
        metal: THREE.MeshStandardMaterial;
        ["Executive.003"]: THREE.MeshStandardMaterial;
        ["Executive__1.003"]: THREE.MeshStandardMaterial;
        ["Executive__2.003"]: THREE.MeshStandardMaterial;
        ["Executive__3.003"]: THREE.MeshStandardMaterial;
        ["Black.081"]: THREE.MeshStandardMaterial;
        ["Brown.033"]: THREE.MeshStandardMaterial;
        ["Plant_Green.033"]: THREE.MeshStandardMaterial;
        ["Black.097"]: THREE.MeshStandardMaterial;
        ["LightMetal.027"]: THREE.MeshStandardMaterial;
        ["White.053"]: THREE.MeshStandardMaterial;
        ["Material.001"]: THREE.MeshStandardMaterial;
        Mousepad: THREE.MeshStandardMaterial;
        _5_Drawer: THREE.MeshStandardMaterial;
        _5_Drawer_1: THREE.MeshStandardMaterial;
        ["mat21.001"]: THREE.MeshStandardMaterial;
        ["mat15.001"]: THREE.MeshStandardMaterial;
        ["White.001"]: THREE.MeshStandardMaterial;
        ["Grey.001"]: THREE.MeshStandardMaterial;
        ["Black.003"]: THREE.MeshStandardMaterial;
        Floor: THREE.MeshStandardMaterial;
        Walls: THREE.MeshStandardMaterial;
        Houseplant_mat1: THREE.MeshStandardMaterial;
    };
    animations: GLTF["animations"];
};

export type TOnReadyReturn = {
    chair: THREE.Object3D;
    phone: THREE.Object3D;
    cup: THREE.Object3D;
    monitor: THREE.Object3D;
    pictureFrame: THREE.Object3D;
    papers: THREE.Object3D;
    mousePad: THREE.Object3D;
};

type TRoomScene = {
    onReady: (returnObjs: TOnReadyReturn) => void;
} & JSX.IntrinsicElements["group"];

export function RoomScene({ onReady, ...props }: TRoomScene) {
    const { nodes, materials } = useGLTF(
        "models/room/room.glb"
    ) as unknown as GLTFResult;
    const chairRef = useRef<THREE.Object3D>(null);
    const phoneRef = useRef<THREE.Object3D>(null);
    const cupRef = useRef<THREE.Object3D>(null);
    const monitorRef = useRef<THREE.Object3D>(null);
    const pictureFrameRef = useRef<THREE.Object3D>(null);
    const papersRef = useRef<THREE.Object3D>(null);
    const mousePadRef = useRef<THREE.Object3D>(null);

    const sceneContext = useContext(SceneContext);
    const handleClick = (event: { eventObject: { uuid: string } }) => {
        if (!sceneContext) return;

        const found = sceneContext.sections.find(
            (section) => section.object3d.uuid == event.eventObject.uuid
        );

        if (found) {
            sceneContext.setActiveSection(found);
        }
    };

    useEffect(() => {
        if (
            !onReady ||
            !chairRef.current ||
            !cupRef.current ||
            !monitorRef.current ||
            !mousePadRef.current ||
            !papersRef.current ||
            !phoneRef.current ||
            !pictureFrameRef.current
        ) {
            return;
        }

        onReady({
            chair: chairRef.current,
            cup: cupRef.current,
            monitor: monitorRef.current,
            mousePad: mousePadRef.current,
            papers: papersRef.current,
            phone: phoneRef.current,
            pictureFrame: pictureFrameRef.current,
        });
    }, [chairRef, onReady]);

    return (
        <group {...props} dispose={null}>
            <group position={[-1.267, 0.343, 9.237]}>
                <group
                    position={[1.455, 0.949, -10.67]}
                    rotation={[-Math.PI / 2, 0, 2.917]}
                    scale={48.098}
                    ref={pictureFrameRef}
                    onClick={handleClick}
                >
                    <mesh
                        geometry={
                            nodes["Blank_Picture_Frame|Node007|Dupli|_1"]
                                .geometry
                        }
                        material={materials["mat21.009"]}
                    />
                    <mesh
                        geometry={
                            nodes["Blank_Picture_Frame|Node007|Dupli|_2"]
                                .geometry
                        }
                        material={materials["mat22.006"]}
                    />
                    <mesh
                        geometry={
                            nodes["Blank_Picture_Frame|Node007|Dupli|_3"]
                                .geometry
                        }
                        material={materials["mat15.007"]}
                    />
                    <mesh
                        geometry={
                            nodes["Blank_Picture_Frame|Node007|Dupli|_4"]
                                .geometry
                        }
                        material={materials["mat24.003"]}
                    />
                </group>
                <group
                    position={[0.792, 0.833, -10.186]}
                    rotation={[-1.571, 0, -0.064]}
                    scale={20.517}
                >
                    <mesh
                        geometry={
                            nodes["Keyboard001|group311988427|Dupli|1_1"]
                                .geometry
                        }
                        material={materials["mat22.011"]}
                    />
                    <mesh
                        geometry={
                            nodes["Keyboard001|group311988427|Dupli|1_2"]
                                .geometry
                        }
                        material={materials["mat21.013"]}
                    />
                    <mesh
                        geometry={
                            nodes["Keyboard001|group311988427|Dupli|1_3"]
                                .geometry
                        }
                        material={materials["mat16.006"]}
                    />
                    <mesh
                        geometry={
                            nodes["Keyboard001|group311988427|Dupli|1_4"]
                                .geometry
                        }
                        material={materials["mat9.002"]}
                    />
                </group>
                <group
                    position={[2.245, 0.22, -10.29]}
                    rotation={[-Math.PI / 2, 0, -1.595]}
                    scale={212.203}
                >
                    <mesh
                        geometry={nodes.Cabinet_Bed_Drawer_Tabl_1.geometry}
                        material={materials.wood}
                    />
                    <mesh
                        geometry={nodes.Cabinet_Bed_Drawer_Tabl_2.geometry}
                        material={materials._defaultMat}
                    />
                    <mesh
                        geometry={nodes.Cabinet_Bed_Drawer_Tabl_3.geometry}
                        material={materials.metal}
                    />
                </group>
                <group
                    position={[0.805, 0.545, -9.252]}
                    rotation={[-Math.PI / 2, 0, -3.093]}
                    scale={2.911}
                    ref={chairRef}
                    onClick={handleClick}
                >
                    <mesh
                        geometry={nodes.Chair003_1.geometry}
                        material={materials["Executive.003"]}
                    />
                    <mesh
                        geometry={nodes.Chair003_2.geometry}
                        material={materials["Executive__1.003"]}
                    />
                    <mesh
                        geometry={nodes.Chair003_3.geometry}
                        material={materials["Executive__2.003"]}
                    />
                    <mesh
                        geometry={nodes.Chair003_4.geometry}
                        material={materials["Executive__3.003"]}
                    />
                </group>
                <group
                    position={[2.922, 0.87, -10.134]}
                    rotation={[Math.PI, -1.547, 0]}
                    scale={10000.001}
                >
                    <mesh
                        geometry={nodes["Houseplant-bfLOqIV5uP_1"].geometry}
                        material={materials["Black.081"]}
                    />
                    <mesh
                        geometry={nodes["Houseplant-bfLOqIV5uP_2"].geometry}
                        material={materials["Brown.033"]}
                    />
                    <mesh
                        geometry={nodes["Houseplant-bfLOqIV5uP_3"].geometry}
                        material={materials["Plant_Green.033"]}
                    />
                </group>
                <group
                    position={[0.221, 1.075, -10.672]}
                    rotation={[-Math.PI / 2, 0, -2.435]}
                    scale={[8561.476, 8561.475, 8561.472]}
                >
                    <mesh
                        geometry={nodes.Light_Desk001_1.geometry}
                        material={materials["Black.097"]}
                    />
                    <mesh
                        geometry={nodes.Light_Desk001_2.geometry}
                        material={materials["LightMetal.027"]}
                    />
                    <mesh
                        geometry={nodes.Light_Desk001_3.geometry}
                        material={materials["White.053"]}
                    />
                </group>
                <mesh
                    geometry={nodes.Mouse.geometry}
                    material={materials["Material.001"]}
                    position={[1.283, 0.825, -10.173]}
                    rotation={[-Math.PI / 2, 0, 0.13]}
                    scale={14736.426}
                />
                <mesh
                    geometry={nodes.Mousepad.geometry}
                    material={materials.Mousepad}
                    position={[1.277, 0.827, -10.185]}
                    rotation={[-Math.PI / 2, 0, 1.547]}
                    scale={[17.231, 20.977, 0.228]}
                    ref={mousePadRef}
                    onClick={handleClick}
                />
                <group
                    position={[0.828, 0.526, -10.42]}
                    rotation={[-Math.PI / 2, 0, -0.024]}
                    scale={3.21}
                >
                    <mesh
                        geometry={nodes.Node003_1.geometry}
                        material={materials._5_Drawer}
                    />
                    <mesh
                        geometry={nodes.Node003_2.geometry}
                        material={materials._5_Drawer_1}
                    />
                </group>
                <group
                    position={[0.192, 0.858, -10.221]}
                    rotation={[-Math.PI / 2, 0, 1.571]}
                    scale={219.88}
                    ref={papersRef}
                    onClick={handleClick}
                >
                    <mesh
                        geometry={nodes.Paper_1.geometry}
                        material={materials["mat21.001"]}
                    />
                    <mesh
                        geometry={nodes.Paper_2.geometry}
                        material={materials["mat15.001"]}
                    />
                </group>
                <group
                    position={[0.491, 0.833, -10.508]}
                    rotation={[Math.PI / 2, 0, -0.451]}
                    scale={5618.099}
                    ref={phoneRef}
                    onClick={handleClick}
                >
                    <mesh
                        geometry={nodes.Phone_1.geometry}
                        material={materials["White.001"]}
                    />
                    <mesh
                        geometry={nodes.Phone_2.geometry}
                        material={materials["Grey.001"]}
                    />
                    <mesh
                        geometry={nodes.Phone_3.geometry}
                        material={materials["Black.003"]}
                    />
                </group>
                <mesh
                    geometry={nodes["Cup001|Cup|Dupli|"].geometry}
                    material={materials["Mat.006"]}
                    position={[1.425, 0.821, -10.407]}
                    rotation={[-Math.PI / 2, 0, 1.025]}
                    scale={0.219}
                    ref={cupRef}
                    onClick={handleClick}
                />
                <mesh
                    geometry={nodes["Monitor001|iMac|Dupli|"].geometry}
                    material={materials["Mat.008"]}
                    position={[0.821, 0.825, -10.675]}
                    rotation={[-Math.PI / 2, 0, -1.631]}
                    scale={1.135}
                    ref={monitorRef}
                    onClick={handleClick}
                />
            </group>
            <group scale={2}>
                <mesh
                    geometry={nodes.Plane.geometry}
                    material={materials.Floor}
                />
                <mesh
                    geometry={nodes.Plane_1.geometry}
                    material={materials.Walls}
                />
            </group>
            <mesh
                geometry={nodes.Houseplant_mesh.geometry}
                material={materials.Houseplant_mat1}
                position={[-1.059, 0.274, 1.286]}
                scale={0.302}
            />
        </group>
    );
}

useGLTF.preload("models/room/room.glb");
